# Use an official MySQL image as the base image
FROM mysql:latest

# Set environment variables for MySQL
ENV MYSQL_ROOT_PASSWORD=password
ENV MYSQL_DATABASE=main

# Expose the MySQL port (default is 3306)
EXPOSE 3306